### ISSUE TITLE
rls support?

### ISSUE THREAD

**Issue by hh9527** [sourcegraph/sublime-lsp#11]
Rust Language Server (https://github.com/jonathandturner/rls) is in alpha stage, will (did) this project support it?

I tried to configure by myself like this:
```json
{
  "clients": [
    {
        "binary": "rls",
        "file_exts": ["rs"],
        "path_additions": [],
        "env": {}
    }
  ]
}
```

But it seemed it does not work. I found the following logs in console:

```txt
lang_service_enabled: True
2017-01-18 17:15:37,469: 24536: DEBUG: Registered binary rls for extension rs
2017-01-18 17:15:37,469: 24536: DEBUG: Looking for client for extension None in None
2017-01-18 17:15:37,469: 24536: DEBUG: Extension None is not supported yet
```

**Comment by keegancsmith** [comment]
LSP protocol has been moving a bit, rust may be using a slightly different version. However, I don't expect it to be that hard to get working. If ya have some time, we will gladly accept PRs to get it working :) cc @uforic

**Comment by alexsaveliev** [comment]
@hh9527 based on log file it seems that you are trying to edit a new file, I am right? Could you please try to open a `folder` containing Rust project and open Rust file there? Our plugin expects folder to be open and active editor contain a file matching given extension(s)...

**Comment by hh9527** [comment]
@alexsaveliev You are right, but when I open a .rs file, it still not works. But this time, it caused by rls, rls is not functional yet for now. :(

**Comment by keegancsmith** [comment]
@alexsaveliev nice catch.
@hh9527 so should we close out this issue until RLS is functional?

**Comment by hh9527** [comment]
@keegancsmith sure, I will check it in my mac book when i back home.

**Comment by sophiajt** [comment]
@hh9527 - one of the devs of rls here.  We'd love to help get it working in the sublime side.

The RLS should be currently functional, but it can be a little tricky to get working (as we're finding out).

**Comment by alexsaveliev** [comment]
claimed fixed by #12, please verify

**Comment by sophiajt** [comment]
Has anyone been able to get this up and running?  I tried this morning, but I feel like I'm missing some steps.

**Comment by alexsaveliev** [comment]
@jonathandturner PTAL at https://github.com/sourcegraph/sublime-lsp/pull/12#issuecomment-284264669
