### ISSUE TITLE
Arguments to language server

### ISSUE THREAD

**Issue by tassosl** [sourcegraph/sublime-lsp#16]
I do not know if that is possible with this plugin, but can you pass command line arguments into a language server executable in the plugin's user config settings?

For example given the following user settings file:
```
{

  "clients": [
    {
      "binary": "some_languageserver --actually_work=true",
      "path_additions": ["/usr/local/bin"],
      "file_exts": ["some"],
    }
  ]
}
```

Will LSP invoke the `some_languageserver` binary passing in true for the value for the `actually_work` flag?

From my testing, it looks like this will not work and I am not sure if there is a way to pass CLI arguments to the language server binary.

**Comment by keegancsmith** [comment]
You can pass the field `"args": ["--actually_work=true"],`
